### ISSUE TITLE
Prepare Presentation Points

### ISSUE THREAD

**Issue by rjehrlich** [rjehrlich/rc-store#25]
- What would you do differently?
- What are you most proud of?
- What would you do next?
- How did you plan your project?
- What did you learn?
- Q & A

**Comment by Crainh2o** [comment]
- What would you do differently? I would have took more notes. Taking notes will only help you in the long run, especially if you wanna come back to the code. 
- What are you most proud of? Im most proud of understanding exactly what I was doing and understood the JWT Token part more.  
- What would you do next? Next I would add our later features to the code.
- How did you plan your project? We planned the project around our everyday lives. We love lounge clothes so why not do a API for clothes to lay around and wear everyday. 
- What did you learn? I learned to relax and look deeply into the code. The answer to debugging a problem is right in front of you. 
- Q & A

**Comment by rjehrlich** [comment]
- What would you do differently?
In the future, I would commit even MORE often than we did. Although I feel like we were committing often, I feel like it can never be too much and committing after each change big or small will only set us up for further success in the future

- What are you most proud of?
I'm most proud of the way we were able to work together and lean on not only each other but so many other resources available to us. We were not afraid to ask questions when we were stuck, or to look at documentation to solve an issue. Throughout the entirety of the project we used the Driver and Navigator approach, constantly switching back and forth with each new step in our project process.

- What would you do next?
I would love to work together on adding our "nice to have features" to further enhance and showcase improvements in our abilities.

- How did you plan your project?

- What did you learn?
I think we really learned the value of consistent communication. Not only the communication necessary in utilizing the Driver/Navigator approach, but the communication that comes with stopping to understand and learn from how the Navigator was approaching the problem

- Q & A
